# Generated by Django 4.1.5 on 2023-01-31 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profit', models.DecimalField(decimal_places=0, max_digits=50)),
                ('risk', models.DecimalField(decimal_places=0, max_digits=50)),
                ('chart', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Invesment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basic_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ManyToManyField(to='main.collection')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='invesments',
            field=models.ManyToManyField(to='main.invesment'),
        ),
    ]
