# Generated by Django 3.2.10 on 2023-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_portfolio_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='collection',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='collection',
            field=models.ManyToManyField(null=True, to='main.Collection'),
        ),
    ]
