# Generated by Django 3.2.10 on 2023-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230131_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='collection',
            field=models.ManyToManyField(to='main.Collection'),
        ),
    ]
